package com.yuehe.app.common;

import com.yuehe.app.interfaces.CustomizedSpecificationRequired;

public enum SaleColumnsEnum implements CustomizedSpecificationRequired {

    ID, EMPLOYEENAME, CLIENTCOSMETICSHOPNAME, CLIENTNAME, BEAUTIFYSKINITEMNAME, CREATECARDDATE, CREATECARDTOTALAMOUNT,
    ITEMNUMBER,RECEIVEDAMOUNT, DISCOUNT, UNPAIDAMOUNT, EARNEDAMOUNT, RECEIVEDEARNEDAMOUNT, UNPAIDEARNEDAMOUNT,
    EMPLOYEEPREMIUM, SHOPPREMIUM,DESCRIPTION;

}